[CI-1286] Toolkit migration
Financial-Times/n-es-client pull request #102
Opened 2022-08-10 11:29 UTC by AlbertoCuberoNavas

[https://financialtimes.atlassian.net/browse/CI-1286](https://financialtimes.atlassian.net/browse/CI-1286)

2022-08-10 14:08 UTC, juanSanchezAlcala requested changes

2022-08-10 14:08 UTC, juanSanchezAlcala commented on package.json
> +	},
husky in package.json can be removed

2022-08-11 09:13 UTC, AlbertoCuberoNavas commented on package.json
> +	},
removed

2022-08-11 13:31 UTC, juanSanchezAlcala approved these changes

2022-08-12 09:16 UTC, merged